config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :issuers
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/issuer.rb
class Issuer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/issuers_controller.rb
class IssuersController < ApplicationController
    def index
        @issuers = Issuer.all
    end

    def new
        @issuer = Issuer.new
    end

    def create
        @issuer = Issuer.new(issuer_params)
        @issuer.save
        redirect_to @issuer
    end

    def show
        @issuer = Issuer.find(params[:id])
    end

    def edit
        @issuer = Issuer.find(params[:id])
    end

    def update
        @issuer = Issuer.find(params[:id])
        if @issuer.update(issuer_params)
            redirect_to @issuer
        else
            render 'edit'
        end
    end

    def destroy
        @issuer = Issuer.find(params[:id])
        @issuer.destroy

        redirect_to issuers_path
    end

    private
    def issuer_params
        params.require(:issuer).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issuer_helper.rb
module IssuerHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/issuers/_form.html.erb
<%= form_with(model: @issuer, local: true) do |form| %>
    <p>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </p>
    <p>
        <%= form.submit %>
    </p>
<%end%>

app/views/issuers/edit.html.erb
<h1>Edit an Issuer</h1>

<%= render 'form', issuers: @issuers %>

app/views/issuers/index.html.erb
<h1>List of All Issuers</h1>

<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th colspan=3></th>
        </tr>
    </thead>
    <tbody>
        <% @issuers.each do |issuer| %>
        <tr>
        <td><%= issuer.id %></td>
        <td><%= issuer.name %></td>
        <td><%= link_to 'Edit', edit_issuer_path(issuer.id) %></td>
        <td><%= link_to 'Delete', issuer_path(issuer.id), method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
        <%end%>
    </tbody>
</table>

<%= link_to 'Create New', new_issuer_path %>

app/views/issuers/new.html.erb
<h1>Create a new issuer</h1>

<%= render 'form'%>

app/views/issuers/show.html.erb
<p>
    <strong>Id:</strong>
    <%= @issuer.id %>
</p>
<p>
    <strong>Name:</strong>
    <%= @issuer.name %>
</p>

<%= link_to 'Show All', issuers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Platform</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Platform</h1>

<%= link_to 'Issuers', controller: 'issuers' %>